import "./globals.css";
import { Inter } from "next/font/google";
import MenuComponent from "@/components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyPortfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <MenuComponent />
          <div className="min-h-screen pt-16 bg-gray-100">
            <div className="bg-slate-900 w-full">{children}</div>
          </div>
      </body>
    </html>
  );
}
