import "./globals.css";
import { Inter } from "next/font/google";
import MenuComponent from "@/components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyPortfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <div className="min-h-screen flex flex-row bg-gray-100">
            <MenuComponent />
            <div className="bg-slate-900  absolute top-0 left-56 w-[calc(100%-14rem)] ">
              {children}
            </div>
          </div>
        </>
      </body>
    </html>
  );
}
